spring:
  datasource: # H2 DB 설정
    url: jdbc:h2:mem:blog_search;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # H2 (http://localhost:8080/h2-console)
  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate:
        format_sql: true